# Generated by Django 6.0.2 on 2026-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('video', models.FileField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Video',
                'verbose_name_plural': 'Hero Videos',
            },
        ),
    ]
