# Generated by Django 6.0.2 on 2026-03-22 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_herovideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('has_sizes', models.BooleanField(default=False)),
                ('has_shoe_sizes', models.BooleanField(default=False)),
                ('has_color', models.BooleanField(default=True)),
                ('has_material', models.BooleanField(default=False)),
                ('has_fragrance_notes', models.BooleanField(default=False)),
                ('has_metal_type', models.BooleanField(default=False)),
                ('has_volume', models.BooleanField(default=False)),
                ('has_weight', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_base_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_heart_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_top_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_purity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('rose_gold', 'Rose Gold')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.producttype'),
        ),
    ]
