# Generated by Django 6.0.2 on 2026-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
