# Generated by Django 6.0.2 on 2026-03-19 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product_name_orderitem_size_name_and_more'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='sellers.seller'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
